services:
  # 网关服务
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "11000:11000"
    env_file:
      - /home/deploy/.env
    environment:
      # 时区设置
      - TZ=Asia/Shanghai
      # Spring Profile
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    network_mode: bridge
